### ISSUE TITLE
[TASK] Import meeting minutes template from Lab 2

### ISSUE THREAD

**Issue by yuvasaro** [yuvasaro/sp24-cse110-lab3#1]
## Description
Set up the repository to contain the contents from Lab 2 including the meeting minutes template.

## Tasks
- [x] Mirror Lab 2 contents into this repository
- [x] Setup GitHub Pages for this repository
- [x] Update README with the new GitHub Pages URL

**Comment by yuvasaro** [comment]
Reopened the issue to display it on the Issues tab.
